### ISSUE TITLE
Problem with PushbulletExeption

### ISSUE THREAD

**Issue by Skytrox27** [rharder/jpushbullet2#6]
Hello,

I have a problem with PushbulletExeption, I have this error : 
```java
[16:13:08 ERROR]: Error occurred while enabling PushbulletAPI (Is it up to date?)
java.lang.NoClassDefFoundError: net/iharder/jpushbullet2/PushbulletException
        at fr.skytrox27.pushbulletapi.Main.onEnable(Main.java:76) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-76236cb-d4e32ce]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.ClassNotFoundException: net.iharder.jpushbullet2.PushbulletException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_79]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_79]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-76236cb-d4e32ce]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-76236cb-d4e32ce]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        ... 12 more
```

Here is my code :
```java
		 PushbulletClient pbClient = new PushbulletClient("SECRET KEY");
		 try{
			 pbClient.sendNote(null, "My First Push", "Great library. All my devices can see this!");
		 }catch(java.lang.Exception e){
			 e.printStackTrace();
		 }
```
Thanks for your help.

**Comment by rharder** [comment]
Well that’s pretty odd if it can find PushbulletClient but it can’t find PushbulletException.  They’re in the same jar file.

I’m not familiar with the minecraft plugin architecture.  Do you have to explicitly list which classes are accessed or anything like that?  Maybe PushbulletClient is being permitted and PushbulletException is being blocked.  The stack trace shows the class loader as coming from org.bukkit.plugin, and I’m just wondering if it’s a policy configuration that’s blocking PushbulletException.

What do you think?  Can you run the pushbullet code in a standalone project?  You might give it a try.

-Rob

**Comment by Skytrox27** [comment]
sorry It's good Bukkit API that blocks its strangely sorry for the inconvenience ! (
I'm french so sorry for the mistakes :p)

**Comment by rharder** [comment]
Glad you found the cause! -Rob
